name: Docker Image

on:
  push:
    branches: [os-checker]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/mirai:latest
  IMAGE_TAR: /tmp/mirai.tar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Create and boot a builder using by default the docker-container driver.
    # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=${{ env.IMAGE_TAR }}

    ######## Local Image ########
    # - name: Build Docker Image
    #   run: docker build -t mirai .

    # - name: Run Docker Image
    #   run: docker run -e CARGO_TERM_COLOR=always mirai
    #############################

    - name: Load Docker Image
      run: |
        docker load --input ${{ env.IMAGE_TAR }}
        docker image ls -a

    - name: Run Docker Image
      run: docker run -e CARGO_TERM_COLOR=always ${{ env.IMAGE }}
